from . import hr_employee
from . import res_company
from . import hr_contract
from . import hr_payslip
from . import ph_employee_ids
from . import employee_ID
from . import company_ID
from . import contribution_manual
from . import payslip_display
from . import employee_contribution_ID